LOST-STATS/lost-stats.github.io

- Contributing/Contributing.md
- Estimation/OLS/non-ses.md
- Estimation/OLS/ols.md
For reference: https://philip-khor.github.io/LOST-STATS.github.io/
> Fix minor typos

- Time_Series/Creating_Timeseries_Dataset.md
I would like to add new branch "Creating Time-series Dataset" under Time-series which provides the way to create time-series dataset for both R and Stata.
> New branch "Creating Time-series Dataset"

- Geo-Spatial/sf_intersect_mapping
> create the sf_intersect_mapping rmd

- Time_Series/ARMA-models.md
Hello,
I've written a page explaining how to estimate an ARMA model in R and Stata that I thought would be suitable to add to LOST-STATS. Please let me know if any changes need to be made/ anything looks off. 
Best,
Robert McDonough
> adding ARMA model page

- Presentation/histograms.md
added a module on how to construct histograms using R (base and ggplot) as well as Stata
> histograms

- Other/create_a_conda_package.md
This is an _extremely_ rough version of how to create a py3k conda feedstock for packages available only on pypi. It should mostly be considered a dump of the process that I followed when adding the `linearmodels` feedstock. However before merging, if there are obvious issues that could make it clearer, then I would love feedback before merging. :-)
> Add creating a conda package

- Summary_Statistics/Summary_Statistics_Tables.md
Added information about options for summary statistic tables in R outside of R packages that output latex code.
> summary statistic tables: skimr and summarytools

- Time_Series/ARCH Model.md
- Time_Series/GARCH Model.md
Add ARCH & GARCH Models
Provide minimal examples using Python, R, Stata for ARCH
Provide examples using Python and R for GARCH
> ADD ARCH & GARCH Models

- Machine_Learning/artificial_neural_network.md
Opted for brevity and clarity in both text and example (which uses scikit-learn's MPL Regressor).
> Added page on artificial neural networks

- Time_Series/creating_time_series_dataset.md
Reading in time series data, casting to `datetime` type, creating custom yr-qtr column.
> Short Python example for time series

- Other/task_scheduling_with_github_actions.md
An attempt to enumerate the steps for how to setup a Github Action that runs on a schedule. There's a lot of steps involved, and the audience is currently aimed at something like, "You know what environment variables and YAML are," so a reasonably advanced user of this repository.
I look to @NickCH-K for whether it needs to be expanded upon or otherwise toned down. :-)
> First draft of task scheduling

- Presentation/Tables/Balance_Tables.md
Hi Y'all, @khwilson Told me about your cool project! I'm adding a demo of balance assessment from the [RItools](https://github.com/markmfredrickson/RITools) package.
> Adding information about xBalance.

- Model_Estimation/GLS/nested_logit.md
I have created a page for nested logit regressions. Currently includes R code example.
> Nested Logit Page Submission

- Desired_Nonexistent_Pages/desired_nonexistent_pages.md
Removed Nested Logit from Desired page as it now has a page.
> Removed Nested Logit from Desired Pages

- Data_Manipulation/Reshaping/reshape_panel_data_from_long_to_wide.md
- Data_Manipulation/Reshaping/reshape_panel_data_from_wide_to_long.md
- Model_Estimation/OLS/fixed_effects_in_linear_regression.md
Adding python code for fixed effect and the code for reshaping using data.table package in R
> Add python code for fixed effect and data.table for reshaping 

- Desired_Nonexistent_Pages/desired_nonexistent_pages.md
- Machine_Learning/Nearest_Neighbor.md
I would like to add KNN in the machine learning section. Thank you!
> Pull request

- Machine_Learning/Nearest_Neighbor.md
I proofread my md file and find one typo. Please update the file by pulling my request. Thank you.
> Correct a typo

- Desired_Nonexistent_Pages/desired_nonexistent_pages.md
- Model_Estimation/GLS/gmm.md
Made a page about the generalized method of moments with two examples in R
> Creating a GMM page

- Desired_Nonexistent_Pages/desired_nonexistent_pages.md
- Model_Estimation/GLS/mixed_logit.md
I added a page for mixed logit models that includes an example for R.  I also removed mixed logits from the desired non-existent pages md.
> Mixed logit page

- Model_Estimation/Research_Design/event_study.md
Wanted to give a few examples of how to make this python example less cumbersome -- hope that's okay!
> streamline python  example

- Data_Manipulation/Reshaping/reshape_panel_data_from_long_to_wide.md
- Data_Manipulation/Reshaping/reshape_panel_data_from_wide_to_long.md
- Data_Manipulation/creating_categorical_variables.md
- Geo-Spatial/merging_shape_files.md
- Model_Estimation/Research_Design/event_study.md
- Other/task_scheduling_with_github_actions.md
- Presentation/Figures/bar_graphs.md
- Presentation/Figures/density_plots.md
- Presentation/Figures/histograms.md
- Presentation/Figures/marginal_effects_plots_for_interactions_with_categorical_variables.md
- Time_Series/ARIMA-models.md
- Time_Series/MA_Model.md
Small amount of cleanup to make sure code samples run (down to about 10 non-working samples, which I think are actual bugs as opposed to silly dependency issues. :-) )
> Some code sample errors

- Time_Series/Rolling_Regression.md
This adds the .md file for the rolling regression
> Adding the Rolling Regression

- Model_Estimation/GLS/quantile_regression.md
- Model_Estimation/OLS/quantile_regression.md
I have added quantile regression to the LOST repository. I was slightly unsure as to whether it should go under the OLS section of model estimation, or if it should be in its own subcategory or in one of the others. I hope this contribution is useful, and I hope to be able to contribute again!
> Added quantile regression to LOST repository.

- Desired_Nonexistent_Pages/desired_nonexistent_pages.md
- Time_Series/Rolling_Regression.md
1. Adding in the Output for the Rolling Regression in the MD. file
2. Deleting Rolling Regression from the Non existant page
> Final Changes to Rolling Regression

- Desired_Nonexistent_Pages/desired_nonexistent_pages.md
- Presentation/Tables/Cross-Tabulation.md
- Added a new md for cross-tabulations in the presentations/tables folder
- Changed desired missing packages
> Add Cross-Tabulations.md

- Presentation/Figures/graph_themes.md
I have created a page for Graph Themes in R; please let me know if I need to change anything about this page. I touched on ggplot themes, ggthemes, and modifying themes using theme() and element(). I also included links to the websites I used or thought were helpful.
> Added the page "Graph Themes"

- Machine_Learning/Nearest_Neighbor.md
> Added R implementation

- Data_Manipulation/Reshaping/reshape_panel_data_from_wide_to_long.md
Existing phrasing had me confused a bit (I thought the wide_to_long was more easy to use than pandas, rather than compared to melt)
> rephrased easy vs hard bit

- Data_Manipulation/creating_a_variable_with_group_calculations.md
I have added a Julia implementation for 'Creating a Variable with Group Calculations' utilising the DataFrames.jl package.
> Add Julia implementation (Creating a Variable with Group Calculations)

- Model_Estimation/OLS/ANOVA.md
The formula for H1 didn't agree with the given explanation. The old version meant that every consecutive pair of means is different, which is not necessarily the case. I propose a different formula.
> Formulation of ANOVA hypotheses

- Data_Manipulation/Combining_Datasets/combining_datasets_horizontal_merge_deterministic.md
- Data_Manipulation/Combining_Datasets/combining_datasets_vertical_combination.md
Added Julia versions of merging dataframes vertically, and doing joins between datasets containing at least one common column.
> Added horizontal and vertical joins

- Presentation/Tables/Cross-Tabulation.md
I mostly followed the Python version.
> Add Julia language to Cross-Tabulation page

- Desired_Nonexistent_Pages/desired_nonexistent_pages.md
- Machine_Learning/artificial_neural_network.md
I've added Julia implementation that mostly corresponds to the Python one but more explicit.
> Julia implementation for ANNs page

- Model_Estimation/OLS/simple_linear_regression.md
Hi! That's me again pushing Julia... 😅
I know, I only ever contribute once a year, but this Hacktoberfest thing indeed pushes me to do so, thus I'd appreciate you adding a `hacktoberfest-accepted` label to the PR, if that's not too much of a hassle... 😺
Also, I'm planning on adding GLM too — should I make a separate PR or add to this one? More PRs are better for Hacktoberfest, but I don't want to bother you too much either.
> Julia implementation of the Simple Linear Regression
